server:
  port: 8060

spring:
  redis:
    cluster:
      nodes[0]: 127.0.0.1:6379
      nodes[1]: 127.0.0.1:6381
      nodes[2]: 127.0.0.1:6382
      nodes[3]: 127.0.0.1:6383
      nodes[4]: 127.0.0.1:6384
      nodes[5]: 127.0.0.1:6385
      max-redirects: 3
    jedis:
      pool:
        max-active: 8
        min-idle: 0
  thymeleaf:
    mode: HTML

  datasource:
    url: jdbc:mysql://localhost:3306/mmall?useSSL=false&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: agytorudhcv11


  session:
    store-type: redis
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB


mybatis:
  mapper-locations: classpath*:mappers/*.xml



bsb:
  mall:
    ftp:
      serverIp: xiyoumobilebackres.xyz
      serverPort: 21
      user: zeng
      password: agytorudhcv11
      serverHttpPrefix: http://xiyoumobilebackres.xyz/
    aliPay:
      callBackUrl: http://2ixehu.natappfree.cc/mall/order/aliPayCallBack
#      callBackUrl: http://www.xiyoumobileback.club:8080/mall/order/aliPayCallBack
    task:
      hour: 2
      lockTimeOut: 5000